### ISSUE TITLE
How to load parameters in component?

### ISSUE THREAD

**Issue by zhihuiLiang** [ros2/demos#587]
I want to load a node in component.There are some parameters in the node.I wrote the launch file like this
```python
def generate_launch_description():
    config = os.path.join(get_package_share_directory(
                            'engineer_bringup'), 'config/engineer_bringup.yaml')

    container = ComposableNodeContainer(
            name='engineer_container',
            namespace='',
            package='rclcpp_components',
            executable='component_container',
            composable_node_descriptions=[
                ComposableNode(
                    package='video_img_publisher',
                    plugin='img_publisher::VideoImgPublisher',
                    name='video_img_publisher',
                    parameters=[config]),
            ],
            output='screen',
    )

    return launch.LaunchDescription([container])
```
And the yaml file like this
```
/video_img_publisher:
  ros__parameters:
    video_path: /home/lzh/test.map4
    fps: 30
    fov: 30.0
    width: 640
    height: 480
```
But the node always run with default parameter.So I want to know how to load the parameters in the component.
